xcopy /Y /E "..\..\..\programs\ResourceServer\ASPNETWebServiceCore" "ASPNETWebServiceCore\"
xcopy /Y /E "..\..\..\files" "ASPNETWebServiceCore\files\"
xcopy /Y /E "..\..\..\programs\OpenTouryoAssemblies\Build_netcore50" "ASPNETWebServiceCore\Assemblies\"
echo F | xcopy /Y /E "..\..\..\files\resource\X509\SHA256RSA_Server.cer" "ASPNETWebServiceCore\X509\SHA256RSA_Server.cer"
copy /Y "ASPNETWebServiceCore.csproj" "ASPNETWebServiceCore\ASPNETWebServiceCore.csproj"
del /Q "Host\Dockerfile"