version: '3.4'
services:
  multipurposeauthsitecore:
    image: osscjpdevinfra/multipurposeauthsitecore:OAuth2OidcArchitOnDocker
    environment:
      - ASPNETCORE_URLS=http://+:5000
      - UseUrl=http://0.0.0.0:5000/
      - RedisConfig=redis
      - RedisInstanceName=redis
      - ConnectionString_SQL=Data Source=sqlserver;Initial Catalog=Northwind;User ID=sa;Password=seigi@123;
      - ConnectionString_MCN=Server=mysql;Database=test;User Id=root;Password=seigi@123;
      - ConnectionString_NPS=HOST=postgres;DATABASE=postgres;USER ID=postgres;PASSWORD=seigi@123;
    ports:
      - "44300:5000"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    networks:
      - common_link


networks:
  common_link:
    external: true