xcopy /Y /E "..\..\..\programs\MultiPurposeAuthSiteCore\MultiPurposeAuthSiteCore" "MultiPurposeAuthSiteCore\"
xcopy /Y /E "..\..\..\files" "MultiPurposeAuthSiteCore\files\"
xcopy /Y /E "..\..\..\programs\OpenTouryoAssemblies\Build_netcore30" "MultiPurposeAuthSiteCore\Assemblies\"
xcopy /Y /E "..\..\..\programs\CommonLibrary\bin\netcore\Debug" "MultiPurposeAuthSiteCore\Assemblies\"
copy /Y "MultiPurposeAuthSiteCore.csproj" "MultiPurposeAuthSiteCore\MultiPurposeAuthSiteCore.csproj"
copy /Y "appsettings.json" "MultiPurposeAuthSiteCore\appsettings.json"
del /Q "MultiPurposeAuthSiteCore\Dockerfile"