xcopy /Y /E "..\..\programs\MultiPurposeAuthSiteCore\MultiPurposeAuthSiteCore" "MultiPurposeAuthSiteCore\"
xcopy /Y /E "..\..\files" "MultiPurposeAuthSiteCore\files\"
xcopy /Y /E "..\..\programs\OpenTouryoAssemblies\Build_netcore30" "MultiPurposeAuthSiteCore\Assemblies\"
xcopy /Y /E "..\..\programs\CommonLibrary\bin\netcore\Debug" "MultiPurposeAuthSiteCore\Assemblies\"
copy /Y ".\MVC_Sample.csproj" "MVC_Sample\MVC_Sample.csproj"
del /Q "MVC_Sample\Dockerfile"